ALTER TABLE "AdminSettings"
ADD COLUMN IF NOT EXISTS "doctorApprovalAlerts" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "clinicRequestAlerts" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "systemAlerts" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "weeklyDigest" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "defaultPageSize" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN IF NOT EXISTS "auditLogRetentionDays" INTEGER NOT NULL DEFAULT 180,
ADD COLUMN IF NOT EXISTS "maintenanceMode" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "deleteConfirmationRequired" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "timezone" TEXT NOT NULL DEFAULT 'Asia/Jakarta';
